# Generated by Django 2.2 on 2019-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackInformation',
            fields=[
                ('artistId', models.IntegerField(primary_key=True, serialize=False)),
                ('artistName', models.CharField(max_length=50)),
                ('trackName', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=3)),
                ('genreName', models.CharField(max_length=50)),
                ('releaseDate', models.DateTimeField()),
            ],
            options={
                'ordering': ['artistName'],
            },
        ),
    ]
