# Generated by Django 2.2 on 2019-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinformation',
            name='country',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='genreName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='releaseDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='trackName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
