# Generated by Django 2.2 on 2019-04-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_auto_20190430_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackinformation',
            options={'ordering': ['trackName']},
        ),
        migrations.AddField(
            model_name='trackinformation',
            name='trackId',
            field=models.IntegerField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='artistId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='genreName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='releaseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='trackName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
