# Generated by Django 2.2 on 2019-04-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_auto_20190430_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInformation',
            fields=[
                ('artistId', models.IntegerField(primary_key=True, serialize=False)),
                ('artistName', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['artistName'],
            },
        ),
        migrations.RemoveField(
            model_name='trackinformation',
            name='artistName',
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_api.ArtistInformation'),
        ),
    ]
