# Generated by Django 2.2 on 2019-05-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0004_auto_20190430_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinformation',
            name='artistId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trackinformation',
            name='trackId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
